---
name: GitHub Super-Linter

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_dispatch: null

  schedule:
    - cron: 17 4 * * 1-5

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: '${{ github.ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build:
    name: GitHub Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          fetch-depth: 0

      # - name: Check branch
      #   id: branch
      #   run: |
      #     date=$(date +%Y_%m_%d)
      #     branch_name="date_$date"
      #     if git show-ref --quiet refs/heads/$branch_name; then
      #       echo "$branch_name branch exists"
      #       echo "::set-output name=exists::true"
      #       exit 0
      #     fi
      #     echo "::set-output name=exists::false"
           
      # - name: Create new branch
      #   if: steps.branch.outputs.exists == 'false'
      #   run: |
      #     date=$(date +%Y_%m_%d)
      #     branch_name="date_$date"
      #     git checkout -b $branch_name
      #     git push -u origin $branch_name
        
      - name: checkout branch
        # if: steps.branch.outputs.exists == 'true'
        run: |
          date=$(date +%Y_%m_%d)
          branch_name="date_$date"
          git checkout $branch_name

      - name: GitHub Super-Linter
        id: super_linter
        uses: github/super-linter/slim@454ba4482ce2cd0c505bc592e83c06e1e37ade61 # v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_STEP_DEBUG: true
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          # yamllint disable rule:line-length
          VALIDATE_GITHUB_ACTIONS: false # yaml This is disabled until Super-Linter ships with a newer version of actionlint supports the new `var` context
          # yamllint enable rule:line-length
          # TODO: Fix all the shell scripts and re-enable these
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_SHELL_SHFMT: false
          
      
      - name: Check for changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git branch
          git add .
          git diff --exit-code || git commit -m "Updates from GitHub Actions Super Linter"
          branch_name=$(git branch --show-current)
          changes=$(git diff origin/main...$branch_name --name-only)
          if [ -z "$changes" ]; then
            echo "No changes detected."
            exit 1
          else
            echo "Changes detected."
            exit 0
          fi

      - name: Push changes
        run: |
          git push 

      - name: Create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_title="GitHub Actions Super Linter workflow"
          pr_body="This PR is a test and can be ignored"
          branch_name=$(git branch --show-current)
          pr_head="${{ github.repository_owner }}:${branch_name}"
          pr_base="main"
          gh pr create --title "$pr_title" --body "$pr_body" --head "$pr_head" --base "$pr_base" --label "code quality"
