---
name: GitHub Super-Linter

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: 17 4 * * 1-5

permissions: read-all

concurrency:
  group: '${{ github.ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  lint:
    name: GitHub Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          fetch-depth: 0

      - name: Generate branch name
        id: branch
        run: |
          date=$(date +%Y_%m_%d)
          name="date_$date"
          echo "name=$name" >> "$GITHUB_OUTPUT"
          if git ls-remote --exit-code --heads origin $name; then
            echo "$name branch exists"
            echo "exists=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "exists=false" >> "$GITHUB_OUTPUT"
           
      - name: Create new branch
        if: steps.branch.outputs.exists == 'false'
        run: |
          git checkout -b ${{ steps.branch.outputs.name }}
          git push -u origin ${{ steps.branch.outputs.name }}
        
      - name: Checkout branch
        if: steps.branch.outputs.exists == 'true'
        run: |
          git checkout ${{ steps.branch.outputs.name }}

      - name: Lint code
        id: super_linter
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_STEP_DEBUG: true
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          # yamllint disable rule:line-length
          VALIDATE_GITHUB_ACTIONS: false # yaml This is disabled until Super-Linter ships with a newer version of actionlint supports the new `var` context
          # yamllint enable rule:line-length
          # TODO: Fix all the shell scripts and re-enable these
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_SHELL_SHFMT: false
          
      - name: Check for changes
        id: check_changes
        run: |
          if ! git diff --quiet; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else 
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi
        
      - name: Add changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: git add .

      - name: Commit changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.name 'Github Actions'
          git config --local user.email 'actions@github.com'
          git commit -m "Superlineter automatic code improvements"

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git push origin ${{ steps.branch.outputs.name }}

      - name: Create pull request
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_title="GitHub Actions Super Linter workflow"
          pr_body="This is an automated pull request raised from Super-Linter changes"
          branch_name=${{ steps.branch.outputs.name }}
          pr_head="${{ github.repository_owner }}:$branch_name"
          pr_base="main"
          gh pr create --title "$pr_title" --body "$pr_body" --head "$pr_head" --base "$pr_base" --label "code-quality"
